### ISSUE TITLE
Using with ES6/Babel

### ISSUE THREAD

**Issue by huston007** [yarax/typelint#2]
Hi! I've just set it up and got this issue: 
```bash
Error while loading rule 'typelint/composite': Unexpected token import
/Users/***/Documents/work/***/src/app.js:1
(function (exports, require, module, __filename, __dirname) { import Auth from './components/auth/auth';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at setSchema (/Users/***/Documents/work/***/node_modules/eslint-plugin-typelint/lib/schemas/formats/json.js:24:28)
    at lookUp (/Users/***/Documents/work/***/node_modules/eslint-plugin-typelint/lib/schemas/formats/json.js:36:12)
```

My .eslintrc.js looks like:
```javascript
module.exports = {
  'extends': [
    'defaults'
  ],
  'parser': 'babel-eslint',
  'plugins': [
    'react',
    'react-native',
    'typelint'
  ],
  'rules': {
    'no-unused-vars': [2, {'vars': 'local', 'args': 'none'}],
    'no-console': 0,
    'quotes': [2, 'single', {'allowTemplateLiterals': true}],
    //ES6
    'constructor-super': 2,
    'arrow-spacing': 2,
    'no-const-assign': 2,
    'no-var': 2,
    'prefer-spread': 2,
    'prefer-template': 2,
    'no-dupe-class-members': 2,
    'no-this-before-super': 2,
    //React
    'react/jsx-uses-react': 2,
    'react/jsx-key': 2,
    'react/no-deprecated': 2,
    'react/jsx-max-props-per-line': [2, {maximum: 4}],
    'react/jsx-uses-vars': 2,
    'react-native/no-unused-styles': 2,
    'react-native/split-platform-components': 2,

    'typelint/composite': 2,
    // 'typelint/primitive': 2
  },
  'env': {
    'es6': true,
    'commonjs': true,
    'mocha': true,
    'node': true
  },
  'globals': {
    'fetch': true,
    'console': true,
    'expect': true
  },
  'settings': {
    'typelint': {
      'models': {
        'json': {
          'dir': './src'
        }
      }
    }
  }
};
```

As you see, I use babel-eslint. What can I do to make it work?

**Comment by yarax** [comment]
Hi!
Thanks for the issue. 
I've created a small project with your config and it seems working fine. 
You can check it out here https://yadi.sk/d/dw2TLCtgt3FAs
I freezed dependencies to the shrinkwrap (just installed default versions of needed libs)
How do you run eslint? Probably there is a mismatching between plugins/versions of local and global libraries.
I would recommend always to run eslint as ./node_modules/.bin/eslint

**Comment by huston007** [comment]
@yarax Okay thank you! If it works for simple project, it seems to be kind of misconfiguration. I'll investigate and report here.

By the way I use eslint from local project's node_modules and I run it by npm script: `"lint": "eslint src"`

**Comment by huston007** [comment]
@yarax actually I didn't succeed with example: 
I installed the dependencies (had to create empty package.json to make npm do that). I use Node 5.7.1, NPM 3.6.0;
Package.json:
```json
{
  "name": "test_typelint",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "lint": "eslint .",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

Output:
```bash
➜  test_typelint  ./node_modules/.bin/eslint .

/Users/***/Documents/github/test_typelint/1.js
  1:16  error  Parsing error: Unexpected token

/Users/***/Documents/github/test_typelint/index.js
  7:15  error  Invalid access to property wrong for type var  typelint/composite

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by yarax** [comment]
The first error is actually real one :) My fault, export and const are not going together, previously I just checked index.js.
But the second is an error from typelint, which means it works properly :)
PS @huston007 According to your package.json eslint is still using globally. 
PS (btw `npm install` works fine with me, just having npm-shrinkwrap.json)

**Comment by huston007** [comment]
@yarax Okay, thanks, will continue investigation. Just for information, npm scripts use binaries from project's node_modules first. Actually I even has no eslint installed globally
```bash
➜  build git:(master) eslint
zsh: command not found: eslint
➜  build git:(master)
```

**Comment by yarax** [comment]
@huston007  Oh, I see. Good to know :) 
So feel free to notify if something else goes wrong

**Comment by huston007** [comment]
@yarax I got what I did wrong. I have javascript (ES6) files in src directory. typelint tried to parse it as model schemas.
Anyway, this issue could help someone faced into same problem. Thanks for you help!
