### ISSUE TITLE
massive console output when composite rule enabled

### ISSUE THREAD

**Issue by Supacoco** [yarax/typelint#4]
Hey, 
First of all Nice work !

I found out that you have a `console.log` in the file `lib/schemas/load.js` 
It generates a massive out put of `##########`

![output](http://i.imgur.com/ZlA6RaE.png)

Keep up the good work :)

**Comment by yarax** [comment]
Oh crap)
I've been using ESLint inside if WebStorm and didn't mention it.
Fixed.
Thanks a lot!
